### ISSUE TITLE
Extend any eslint-config-* config rules?

### ISSUE THREAD

**Issue by Tailzip** [thoughtbot/hound-eslint#14]
Hi,

I'm trying to extend Airbnb's ESLint base rules, but I'm getting an error: 

`Error parsing config for: eslint.`

Here is what my `.eslintrc` file looks like:
```json
{
  "extends": "airbnb/base",
  "rules": {
    "no-console": 0
  }
}
```

Thanks!

**Comment by teoljungberg** [comment]
Thanks for reporting this @Tailzip ! 

I've opened #15 to allow airbnb's styleguide to be used

**Comment by teoljungberg** [comment]
I can give you a bit of back story - we are installing plugins case by case, so we can control which plugins are installed on our servers.

**Comment by Tailzip** [comment]
Great!

I ended up putting ALL Airbnb's rules in the `.eslintrc` config file for the time being. Not ideal, but, at least, it's working :)

**Comment by teoljungberg** [comment]
#15 is merged and deployed now.

Thanks for reporting this, @Tailzip!

**Comment by Tailzip** [comment]
Awesome! Thanks for your reactivity!
